### ISSUE TITLE
camel-servlet not working on tomcat9

### ISSUE THREAD

**Issue by rdoshi29** [PickledDragon/60227230-camel-servlet-example#10]
Hi,
I tried deploying this project with tomcat and the servlet is not working with tomcat, the base url is working fine but /camel/hello is giving 404 error.
Any help is appreciated.
Thank you

**Comment by PickledDragon** [comment]
What do you see on your tomcat logs when an http 404 is logged?

As written in the README.md, you should try to access the camel servlet at : http://localhost:8080/camel-example-servlet/camel/hello if you running it locally. Is that what you're doing? or just http://localhost:8080/camel/hello

Additionally this service is expected to do plumbing towards another service that listens on http://localhost:8000/ do you have that running?

**Comment by PickledDragon** [comment]
I just ran it on Tomcat 9 (docker image) and the code does work. Camel Servlet does start, it accepts connections and even tries to forward to upstream and then fails due to the apparent reason that there is no upstream server. 

```logs
➜ docker run -it --rm -p 8888:8080 -v /tmp/camel-servlet-demo/60227230-camel-servlet-example/target/camel-example-servlet.war:/usr/local/tomcat/webapps/camel-example-servlet.war tomcat:9.0
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /opt/java/openjdk
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
18-Jul-2022 19:52:27.447 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.64
18-Jul-2022 19:52:27.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 2 2022 19:08:46 UTC
18-Jul-2022 19:52:27.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.64.0
18-Jul-2022 19:52:27.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
18-Jul-2022 19:52:27.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.10.25-linuxkit
18-Jul-2022 19:52:27.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
18-Jul-2022 19:52:27.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
18-Jul-2022 19:52:27.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           17.0.3+7
18-Jul-2022 19:52:27.453 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
18-Jul-2022 19:52:27.453 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat

18-Jul-2022 19:52:27.453 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
18-Jul-2022 19:52:27.462 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
18-Jul-2022 19:52:27.462 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
18-Jul-2022 19:52:27.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
18-Jul-2022 19:52:27.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
18-Jul-2022 19:52:27.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
18-Jul-2022 19:52:27.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
18-Jul-2022 19:52:27.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
18-Jul-2022 19:52:27.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
18-Jul-2022 19:52:27.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
18-Jul-2022 19:52:27.464 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
18-Jul-2022 19:52:27.464 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
18-Jul-2022 19:52:27.464 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
18-Jul-2022 19:52:27.464 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
18-Jul-2022 19:52:27.464 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
18-Jul-2022 19:52:27.467 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.33] using APR version [1.7.0].
18-Jul-2022 19:52:27.468 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
18-Jul-2022 19:52:27.468 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
18-Jul-2022 19:52:27.471 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
18-Jul-2022 19:52:27.666 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
18-Jul-2022 19:52:27.682 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [347] milliseconds
18-Jul-2022 19:52:27.714 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
18-Jul-2022 19:52:27.714 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.64]
18-Jul-2022 19:52:27.731 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/camel-example-servlet.war]
18-Jul-2022 19:52:28.212 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2022-07-18 19:52:28,432 [main           ] INFO  CamelServletContextListener    - CamelContextServletListener initializing ...
2022-07-18 19:52:28,562 [main           ] INFO  ServletCamelContext            - Apache Camel 2.25.0 (CamelContext: MyCamel) is starting
2022-07-18 19:52:28,563 [main           ] INFO  ManagedManagementStrategy      - JMX is enabled
2022-07-18 19:52:28,651 [main           ] INFO  DefaultTypeConverter           - Type converters loaded (core: 195, classpath: 9)
2022-07-18 19:52:28,761 [main           ] INFO  ServletCamelContext            - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2022-07-18 19:52:28,795 [main           ] INFO  ServletCamelContext            - Route: HTTP Bridging Route started and consuming from: servlet:/hello?matchOnUriPrefix=true
2022-07-18 19:52:28,796 [main           ] INFO  ServletCamelContext            - Total 1 routes, of which 1 are started
2022-07-18 19:52:28,796 [main           ] INFO  ServletCamelContext            - Apache Camel 2.25.0 (CamelContext: MyCamel) started in 0.237 seconds
2022-07-18 19:52:28,797 [main           ] INFO  CamelServletContextListener    - CamelContextServletListener initialized
2022-07-18 19:52:28,810 [main           ] INFO  CamelHttpTransportServlet      - Initialized CamelHttpTransportServlet[name=CamelServlet, contextPath=/camel-example-servlet]
18-Jul-2022 19:52:28.817 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/camel-example-servlet.war] has finished in [1,085] ms
18-Jul-2022 19:52:28.820 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-Jul-2022 19:52:28.829 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1147] milliseconds
2022-07-18 19:53:07,903 [nio-8080-exec-4] INFO  HTTP Bridging Route            - Request: GET to /camel-example-servlet/camel/hello
18-Jul-2022 19:53:07.931 INFO [http-nio-8080-exec-4] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (java.net.ConnectException) caught when processing request: Connection refused
18-Jul-2022 19:53:07.931 INFO [http-nio-8080-exec-4] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
18-Jul-2022 19:53:07.932 INFO [http-nio-8080-exec-4] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (java.net.ConnectException) caught when processing request: Connection refused
18-Jul-2022 19:53:07.932 INFO [http-nio-8080-exec-4] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
18-Jul-2022 19:53:07.932 INFO [http-nio-8080-exec-4] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry I/O exception (java.net.ConnectException) caught when processing request: Connection refused
18-Jul-2022 19:53:07.933 INFO [http-nio-8080-exec-4] org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry Retrying request
2022-07-18 19:53:07,935 [nio-8080-exec-4] ERROR DefaultErrorHandler            - Failed delivery for (MessageId: ID-1e6bdb90c9e7-1658173948479-0-2 on ExchangeId: ID-1e6bdb90c9e7-1658173948479-0-1). Exhausted after delivery attempt: 1 caught: java.net.ConnectException: Connection refused

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[HTTP Bridging Rout] [HTTP Bridging Rout] [servlet:/hello?matchOnUriPrefix=true                                          ] [        35]
[HTTP Bridging Rout] [log1              ] [log                                                                           ] [         3]
[HTTP Bridging Rout] [to1               ] [http://localhost:8000?bridgeEndpoint=true                                     ] [        29]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at java.net.Socket.connect(Socket.java:583) ~[?:?]
	at java.net.Socket.<init>(Socket.java:507) ~[?:?]
	at java.net.Socket.<init>(Socket.java:361) ~[?:?]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[commons-httpclient-3.1.jar:?]
	at org.apache.camel.component.http.HttpProducer.executeMethod(HttpProducer.java:287) ~[camel-http-2.25.0.jar:2.25.0]
	at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:169) ~[camel-http-2.25.0.jar:2.25.0]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97) [camel-core-2.25.0.jar:2.25.0]
	at org.apache.camel.http.common.CamelServlet.doService(CamelServlet.java:213) [camel-http-common-2.25.0.jar:2.25.0]
	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:79) [camel-http-common-2.25.0.jar:2.25.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.64]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.64]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.64]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.64]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.64]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.64]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.64]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.64]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.64]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.64]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.64]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.64]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [catalina.jar:9.0.64]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-coyote.jar:9.0.64]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.64]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) [tomcat-coyote.jar:9.0.64]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787) [tomcat-coyote.jar:9.0.64]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.64]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.64]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.64]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.64]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

From the browser
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/4092768/179606514-8a4c187e-93f7-4019-af49-4fbd05b895eb.png">

**Comment by PickledDragon** [comment]
Closing the issue since the code does exactly what it is designed for.
